### ISSUE TITLE
Add README.md files for (Variables, Var, Let, Const, Datatypes and Operators) 

### ISSUE THREAD

**Issue by utkarsh006** [arkalsekar/Learn-Javascript#3]
Hey Admin! I want to contribute README.md files for the 6 javascript files mentioned in the title of this issue. This documentation would help user to understand your Repository better and ensures better readability of the files. Kindly, assign the issue to me.

**Comment by nishkarsh800** [comment]
@arkalsekar kindly give labels the issues as "hacktoberfest"

**Comment by utkarsh006** [comment]
@utkarsh006 Kindly labels the issues as "hacktoberfest"
