### ISSUE TITLE
Some typos need tobe fixed. 

### ISSUE THREAD

**Issue by arkalsekar** [arkalsekar/Learn-Javascript#6]
Hey Folks. 
I noticed some typos while linking each file in the Readme File. Would love someone to fix them as it's a good start for Beginners in HacktoberFest.

Thanks

**Comment by astitvaveergarg** [comment]
Hey, I would like to Contribute, Please Assign this issue to me.

**Comment by abhinavjoshicse** [comment]
hey! I would like to contribute in this, please assign this issue to me.
thank you!

**Comment by vikash485** [comment]
Hey @arkalsekar, can I contribute to this issue?

**Comment by arkalsekar** [comment]
> Hey @arkalsekar, can I contribute to this issue?

Yep, you can. I have assigned you as well.

**Comment by SonakshiChauhan** [comment]
Hey Please Can I contribute @arkalsekar
